export const STAFF_ROLES = Object.freeze({
  ADMIN: "ADMIN",
  SOC: "SOC",
  ENGINEER: "ENGINEER",
  IR: "IR",
  AUDITOR: "AUDITOR",
});

export function normalizeStaffRole(value) {
  if (!value || typeof value !== "string") return null;

  const normalized = value.trim().toUpperCase();

  return Object.values(STAFF_ROLES).includes(normalized) ? normalized : null;
}

export const ROLE_ACCESS = Object.freeze({
  ALERTS: [STAFF_ROLES.ADMIN, STAFF_ROLES.SOC, STAFF_ROLES.ENGINEER, STAFF_ROLES.IR, STAFF_ROLES.AUDITOR],
  METRICS: [STAFF_ROLES.ADMIN, STAFF_ROLES.SOC, STAFF_ROLES.ENGINEER, STAFF_ROLES.AUDITOR],
  HANDSHAKES: [STAFF_ROLES.ADMIN, STAFF_ROLES.SOC, STAFF_ROLES.ENGINEER, STAFF_ROLES.AUDITOR],
  EVENT_LOGS: [STAFF_ROLES.ADMIN, STAFF_ROLES.SOC, STAFF_ROLES.AUDITOR],
  ANOMALIES: [STAFF_ROLES.ADMIN, STAFF_ROLES.SOC, STAFF_ROLES.ENGINEER, STAFF_ROLES.IR, STAFF_ROLES.AUDITOR],
  REPLAY_ATTACKS: [STAFF_ROLES.ADMIN, STAFF_ROLES.SOC, STAFF_ROLES.ENGINEER, STAFF_ROLES.IR, STAFF_ROLES.AUDITOR],
  HANDSHAKE_READ: [STAFF_ROLES.ADMIN, STAFF_ROLES.SOC, STAFF_ROLES.ENGINEER, STAFF_ROLES.AUDITOR],
});